# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
    ports:
      - "${DB_PORT}:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app:
    # Indique qu'on utilise les varibales d'environement de notre projet dans l'image docker 
    env_file:
      - .env
    # build: .
    image: sofiane67/api-app:latest
    restart: always
    ports:
      - "5600:5600"
    depends_on:
      - db

